language: php
os: linux

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

matrix:
  allow_failures:
    - php: 7.2
  fast_finish: true

install:
  - composer install --no-interaction

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  # Submit coverage report to codecov.io
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: always

# cache composer for faster tests
cache:
  directories:
    - vendor
    - $HOME/.cache/composer